version: '2'
services:
    ui:
        container_name: "corp-hq-ui"
        build: ./app/ui
        ports:
            - 8080:80
    api:
        container_name: "corp-hq-api"
        build: ./app/api
        ports:
            - 5000:80
        environment:
            - MONGO_CONNECTION=mongodb://127.0.0.1:27017/corp-hq
    runner:
        container_name: "corp-hq-runner"
        image: "corp-hq-runner"
        environment:
            - MONGO_CONNECTION=mongodb://mongo:27017/corp-hq
            - RABBIT_IP=rabbit
        links:
            - "mongodb:mongo"
            - "rabbitmq:rabbit"
    mongodb:
        container_name: "mongodb"
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./mongo-data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null  # --quiet
    rabbitmq:
        image: "rabbitmq:management-alpine"
        hostname: "rabbitmq"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        volumes:
            - ./docker-compose-files/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        ports:
            - 15672:15672
            - 5672:5672
        labels:
            NAME: "rabbitmq1"
